#These are properties serialized from an IA installer for use with an IA uninstaller.
#Sat Jul 11 18:58:28 IST 2020
-fileOverwrite_/home/manuj/APPS/CMapTools/licenses/jakarta-poi-license.txt=Yes
CHOSEN_INSTALL_FEATURE_2=Applica
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/axiom-impl.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/wsServer-client.jar=Yes
CHOSEN_INSTALL_SET=Advanced
CHOSEN_INSTALL_FEATURE_1=Advance
-fileOverwrite_/home/manuj/APPS/CMapTools/help/CmapHelp_fi/index.html=Yes
IA_UPGRADE_BASE_VERSION=
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/java-json.jar=Yes
USER_PROFILE=
STOP_RECORDER=0
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/mail.jar=Yes
IA_RESPONSEFILE_PATH=
CHOSEN_INSTALL_BUNDLE_LIST=Advance,Applica
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/libgomp.so.1=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/xml-apis.jar=Yes
CHOSEN_INSTALL_BUNDLE_2=Applica
NO_AUTO_RECORDER=1
CHOSEN_INSTALL_BUNDLE_1=Advance
DEPENDENCY_STATUS=success
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/commons-codec-1.6.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/libtiff.so.4=Yes
DEPENDENCY_REPORT=
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/updater.jar=Yes
EMPTY_STRING=
EXTRACTOR_DIR=/home/manuj/Installers/LINUX/APPS/CMapTools
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/wordnetClient.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/stax-api-1.0.jar=Yes
DELETE_USERIDS=0
NO_LOGS=1
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/commons-io-2.2.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/libjpeg.so.62=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/libwmflite-0.2.so.7=Yes
MAC_CHEWABLE=
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/xercesImpl.jar=Yes
WIN_START_MENU=
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/poi-2.5.1-final-20040804.jar=Yes
WIN_WINDOWS=
MACX_USER_APPLICATIONS=
SKIP_UNINSTALL=false
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/commons-logging.jar=Yes
IA_UPGRADE_BASE_LOCATION=
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/commons-beanutils.jar=Yes
INSTALLER_JDK_HOME=
-fileOverwrite_/home/manuj/APPS/CMapTools/licenses/JAF-v1.0.1-license.txt=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/templates/Gray\ On\ White.cxl=Yes
CONFIGURATION=$CHOSEN_INSTALL_SET$
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/freehep-graphicsio-java-2.3.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/libavdevice.a=Yes
SYSTEM_DRIVE_ROOT=/
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/poi-scratchpad-2.5.1-final-20040804.jar=Yes
PROGRAMS_DIR_32=/home/manuj
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/FontBox-0.1.0-dev.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/PDFBox-0.7.3-dev.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/libavutil.a=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/nlk.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/modules.xml=Yes
SYSTEM_32=/usr/local/bin
CHOSEN_INSTALL_FEATURE_NUM=2
INSTALL_SUCCESS=WARNING
INSTALL_DRIVE_ROOT=/
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/freehep-graphicsio-emf-2.3.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/licenses/CmapTools-license.txt=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/freehep-graphicsio-pdf-2.3.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/libswresample.a=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/libICE.so.6=Yes
NULL=
AUTO_RECORDER=0
LOGS=0
DEPENDENCY_FAILURES=
UNIX_USR_LOCAL_BIN=/usr/local/bin
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/tm-extractors-0.4.jar=Yes
FREE_DISK_SPACE_MEGABYTES=155053
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/DefaultStyleSheet.cxl=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/libavformat.a=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/poi-contrib-2.5.1-final-20040804.jar=Yes
INSTALLER_JAVA_EXECUTABLE=/home/manuj/APPS/CMapTools/jre/bin/java
LOGS_PREFIX=cmaptools
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/axiom-api.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/symantec.jar=Yes
WIN_PROGRAMS_MENU=
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/libfreetype.so.6=Yes
FREE_DISK_SPACE_BYTES=162585632768
do_not_use_dummy=
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/freehep-graphicsio-swf-2.3.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/pkgconfig/libavformat.pc=Yes
STARTUP=
FREE_DISK_SPACE_KILOBYTES=158775032
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/commons-beanutils-core.jar=Yes
WIN_QUICK_LAUNCH_BAR=/home/manuj
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/openide-lookup-1.9-patched-1.0.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/licenses/jakarta-log4j-license.txt=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/socks.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/commons-collections.jar=Yes
PRODUCT_NAME=IHMC CmapTools v6.04
USER_HOME=/home/manuj
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/pkgconfig/libswscale.pc=Yes
BUILD_TYPE=public
-fileOverwrite_/home/manuj/APPS/CMapTools/licenses/winlaf-license.txt=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/templates/White\ On\ White.cxl=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/ffmpeg=Yes
INSTALLER_TITLE=IHMC CmapTools v6.04
DEVELOPER_DISK_SPACE_ADDITIONAL=
pki.ldap.port=389
CHOSEN_INSTALL_FEATURE_LIST=Advance,Applica
UNIX_OPT=/opt
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/jdom-1.0.jar=Yes
UNIX_USR_BIN=/usr/bin
USER_MAGIC_FOLDER_25=
KEEP_USERIDS=1
USER_MAGIC_FOLDER_24=
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/cmapclientservices.jar=Yes
USER_MAGIC_FOLDER_23=
USER_MAGIC_FOLDER_22=
USER_MYCMAPS=/home/manuj/My_Cmaps
USER_MAGIC_FOLDER_21=
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/CmapTools.lax=Yes
USER_MAGIC_FOLDER_20=
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/AppleStubs.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/licenses/lucene-license.txt=Yes
WIN_COMMON_START_MENU=
-fileOverwrite_/home/manuj/APPS/CMapTools/help/index.html=Yes
USER_MAGIC_FOLDER_19=
WIN_COMMON_STARTUP=
USER_MAGIC_FOLDER_18=
CHOSEN_INSTALL_FEATURE_LIST_LONG=Advance Configuration,Application
PROGRAMS_DIR=/home/manuj
USER_MAGIC_FOLDER_17=
USER_MAGIC_FOLDER_16=
USER_MAGIC_FOLDER_15=
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/pkgconfig/libavcodec.pc=Yes
USER_MAGIC_FOLDER_14=
FREE_DISK_SPACE_GIGABYTES=151
USER_MAGIC_FOLDER_13=
USER_MAGIC_FOLDER_12=
pki.keystore.password=$NULL$
pki.ca.certificate=$NULL$
USER_MAGIC_FOLDER_11=
DO_NOT_INSTALL=Do Not Install
USER_MAGIC_FOLDER_10=
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/concurrent.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/lucene-core-2.4-dev.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/commons-digester.jar=Yes
DOLLAR=$
WIN_COMMON_PROGRAMS_MENU=
USER_SHORTCUTS=Do Not Install
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/freehep-graphicsio-svg-2.3.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/jniregistry.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/Updater.lax=Yes
PRODUCT_ID=dda6c534-1ec1-11b2-be59-eb78986748b5
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/jmyspell-1.0.0-beta1.jar=Yes
COMMA=,
INSTALLER_MERGE_MODULE=
pki.enable=false
DEPENDENCY_SUCCESSES=
pki.ldap.host=$NULL$
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/wstx-asl-2.9.3.jar=Yes
FONTS=
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/pkgconfig/libavutil.pc=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/help/CmapHelp_es/index.html=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/licenses/tm-extractors-license.txt=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/pkgconfig/libswresample.pc=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/UninstallerData/Change\ CmapTools\ Installation.lax=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/jas-plotter-2.2.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/freehep-graphicsbase-2.3.jar=Yes
REQUIRED_DISK_SPACE_MEGABYTES=239
BUILD_VERSION=public
InstallFolder=1
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/templates/Black\ On\ Gray.cxl=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/templates/White\ On\ Dark\ Blue.cxl=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/slp.jar=Yes
INSTALLER_JAVA_DOT_HOME=/home/manuj/APPS/CMapTools/jre
DESKTOP=/home/manuj/Desktop
JAVA_HOME=/home/manuj/APPS/CMapTools/jre
SYSTEM=/usr/local/bin
-fileOverwrite_/home/manuj/APPS/CMapTools/licenses/JavaMailv1.2-license.txt=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/licenses/PDFBox-license.txt=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/libSM.so.6=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/commons-beanutils-bean-collections.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/libjasper.so.1=Yes
LOGS_NO=3
MAC_APPLE_MENU=
REQUIRED_DISK_SPACE_KILOBYTES=244986
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/templates/Orange\ On\ Black.cxl=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/templates/Beige\ On\ Dark\ Green.cxl=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/log4j-1.2.12.jar=Yes
\\=$prop.file.separator$
MAC_CONTROL_PANELS=
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/pkgconfig/libavdevice.pc=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/freehep-graphicsio-ps-2.3.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/templates/White\ On\ Light\ Blue.cxl=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/imgman=Yes
REQUIRED_DISK_SPACE_BYTES=250865702
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/JimiProClasses.zip=Yes
USER_MAGIC_FOLDER_9=
LOGS_PATH=%h/CmapToolsLogs
CHOSEN_INSTALL_BUNDLE_NUM=2
USER_MAGIC_FOLDER_8=
USER_MAGIC_FOLDER_7=
USER_MAGIC_FOLDER_6=
USER_MAGIC_FOLDER_5=
IA_CUSTOM_CODE_ZIP_SIZE=0
USER_MAGIC_FOLDER_4=
USER_MAGIC_FOLDER_3=
USER_MAGIC_FOLDER_2=
USER_MAGIC_FOLDER_1=
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/libpng12.so.0=Yes
JRE_VERSION=1.7.0_60
USER_INSTALL_DIR=/home/manuj/APPS/CMapTools
;=$prop.path.separator$
\:=$prop.path.separator$
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/libavfilter.a=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/libavcodec.a=Yes
OS400_INSTALL_DIR=/IHMC CmapTools v6.04
OVERWRITE_IA_CHMOD=false
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/cmaptools.cfg=Yes
TEMP_DIR=/tmp
/=$prop.file.separator$
MAC_EXTENSIONS=
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/templates/Blue\ On\ Dark\ Blue.cxl=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/freehep-graphics2d-2.3.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/winlaf-0.5.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/mscrypto.jar=Yes
pki.keystore=$NULL$
NO_STOP_RECORDER=1
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/freehep-graphicsio-2.3.jar=Yes
LOGS_SIZE=5242880
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/freehep-io-2.2.2.jar=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/readme.txt=Yes
MAC_PREFERENCES=
IA_CLASSPATH=../classes\:../classes/core.jar\:../classes/nlk.jar\:../classes/slp.jar\:../classes/activation.jar\:../classes/JimiProClasses.zip\:../classes/mail.jar\:../classes/symantec.jar\:../classes/jniregistry.jar\:../classes/socks.jar\:../classes/AppleStubs.jar\:../classes/wsServer-client.jar\:../classes/xercesImpl.jar\:../classes/xml-apis.jar\:../classes/tm-extractors-0.4.jar\:../classes/concurrent.jar\:../classes/wordnetClient.jar\:../classes/winlaf-0.5.jar\:../classes/poi-scratchpad-2.5.1-final-20040804.jar\:../classes/poi-contrib-2.5.1-final-20040804.jar\:../classes/commons-digester.jar\:../classes/commons-collections.jar\:../classes/commons-beanutils.jar\:../classes/commons-beanutils-core.jar\:../classes/commons-beanutils-bean-collections.jar\:../classes/PDFBox-0.7.3-dev.jar\:../classes/FontBox-0.1.0-dev.jar\:../classes/log4j-1.2.12.jar\:../classes/poi-2.5.1-final-20040804.jar\:../classes/jmyspell-1.0.0-beta1.jar\:../classes/ldapbp.jar\:../classes/commons-logging.jar\:../classes/mscrypto.jar\:../classes/wstx-asl-2.9.3.jar\:../classes/stax-api-1.0.jar\:../classes/axiom-impl.jar\:../classes/axiom-api.jar\:../classes/lucene-core-2.4-dev.jar\:../classes/openide-lookup-1.9-patched-1.0.jar\:../classes/jdom-1.0.jar\:../classes/jas-plotter-2.2.jar\:../classes/commons-io-2.2.jar\:../classes/commons-codec-1.6.jar\:../classes/freehep-io-2.2.2.jar\:../classes/freehep-graphicsio-swf-2.3.jar\:../classes/freehep-graphicsio-svg-2.3.jar\:../classes/freehep-graphicsio-ps-2.3.jar\:../classes/freehep-graphicsio-pdf-2.3.jar\:../classes/freehep-graphicsio-java-2.3.jar\:../classes/freehep-graphicsio-emf-2.3.jar\:../classes/freehep-graphicsio-2.3.jar\:../classes/freehep-graphicsbase-2.3.jar\:../classes/freehep-graphics2d-2.3.jar\:../classes/java-json.jar
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/slp.conf=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/libswscale.a=Yes
SHORTCUT_NAME=Link
PRODUCT_VERSION_NUMBER=6.0.4.0
CHOSEN_INSTALL_BUNDLE_LIST_LONG=Advance Configuration,Application
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/templates/Beige\ On\ White.cxl=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/activation.jar=Yes
MACX_DOCK=
PROGRAMS_DIR_64=/home/manuj
REQUIRED_DISK_SPACE_GIGABYTES=0
UNIX_USER_HOME=/home/manuj
EXTRACTOR_EXECUTABLE=/home/manuj/Installers/LINUX/APPS/CMapTools/Linux64CmapTools_v6.04_09-24-19.bin
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/ldapbp.jar=Yes
IA_GLOBAL_REG_LOCATION=/home/manuj/.com.zerog.registry.xml
pki.ldap.mode=tls
SYSTEM_64=/usr/local/bin
-fileOverwrite_/home/manuj/APPS/CMapTools/bin/places.txt=Yes
-fileOverwrite_/home/manuj/APPS/CMapTools/classes/core.jar=Yes
pki.ms.cert=$NULL$
IA_INSTALLER_STATUS=WARNING
WIN_COMMON_DESKTOP=
-fileOverwrite_/home/manuj/APPS/CMapTools/lib/pkgconfig/libavfilter.pc=Yes
