# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Sep 24 20:46:48 2022
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2022.9.24
source:
  sha256: 0d9c601124e5a6ba9712dbc60d9c53c21e34f5f641fe83002317394311bdce14
  url: https://pypi.io/packages/source/c/certifi/certifi-2022.9.24.tar.gz
build:
  number: '0'
  string: ha878542_0
requirements:
  build: []
  run: []
test:
  commands:
    - test -f "${PREFIX}/ssl/cacert.pem"
    - test -f "${PREFIX}/ssl/cert.pem"
    - curl --cacert "${PREFIX}/ssl/cacert.pem" https://www.google.com
  requires:
    - curl
about:
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: ISC
  license_file: LICENSE
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
