# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /feedstock/recipe, last modified Tue Sep 20 01:50:17 2022
# ------------------------------------------------

package:
  name: google-api-core
  version: 2.10.1
source:
  sha256: e16c15a11789bc5a3457afb2818a3540a03f341e6e710d7f9bbf6cde2ef4a7c8
  url: https://pypi.org/packages/source/g/google-api-core/google-api-core-2.10.1.tar.gz
build:
  number: '0'
  script: python -m pip install . -vv --no-deps
  string: py39h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - ca-certificates 2022.07.19 h06a4308_0
    - certifi 2022.9.14 py39h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.3 he6710b0_2
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - ncurses 6.3 h5eee18b_3
    - openssl 1.1.1q h7f8727e_0
    - pip 22.1.2 py39h06a4308_0
    - python 3.9.13 haa1d7c7_1
    - readline 8.1.2 h7f8727e_1
    - setuptools 63.4.1 py39h06a4308_0
    - sqlite 3.39.2 h5082296_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2022c h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7f8727e_1
    - zlib 1.2.12 h5eee18b_3
  run:
    - google-auth >=1.25.0,<3.0dev
    - googleapis-common-protos >=1.56.2,<2.0dev
    - protobuf >=3.20.1
    - python >=3.9,<3.10.0a0
    - requests >=2.18.0,<3.0.0dev
  run_constrained:
    - grpcio >=1.33.2,<2.0dev
    - grpcio-gcp >=0.2.2,<1.0dev
    - grpcio-status >=1.33.2,<2.0dev
about:
  description: 'Core Library for Google Client Libraries

    -------------------------

    This library is not meant to stand-alone. Instead it defines common helpers used
    by

    all Google API clients. For more information, see the documentation.

    '
  dev_url: https://github.com/googleapis/python-api-core
  doc_source_url: https://github.com/googleapis/python-api-core/tree/main/docs
  doc_url: https://googleapis.dev/python/google-api-core/latest/index.html
  home: https://github.com/googleapis/python-api-core
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Core Library for Google Client Libraries
extra:
  copy_test_source_files: true
  feedstock-name: google-api-core
  final: true
  flow_run_id: d2c5bce6-06d3-4028-9709-3ae252bf336a
  recipe-maintainers:
    - BrentDorsey
    - leahecole
    - parthea
    - tswast
  remote_url: git@github.com:AnacondaRecipes/google-api-core-feedstock.git
  sha: d6978076890fa71816b0968db0bd9088c20c099e
