# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Aug 25 14:18:01 2022
# ------------------------------------------------

package:
  name: yarl
  version: 1.8.1
source:
  fn: yarl-1.8.1.tar.gz
  sha256: af887845b8c2e060eb5605ff72b6f2dd2aab7a761379373fd89d314f4752abbf
  url: https://pypi.io/packages/source/y/yarl/yarl-1.8.1.tar.gz
build:
  number: '0'
  script: /opt/conda/conda-bld/yarl_1661437085904/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps -vv
  string: py39h5eee18b_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - ca-certificates 2022.07.19 h06a4308_0
    - certifi 2022.6.15 py39h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.3 he6710b0_2
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - ncurses 6.3 h5eee18b_3
    - openssl 1.1.1q h7f8727e_0
    - pip 22.1.2 py39h06a4308_0
    - python 3.9.12 h12debd9_1
    - readline 8.1.2 h7f8727e_1
    - setuptools 63.4.1 py39h06a4308_0
    - sqlite 3.39.2 h5082296_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2022a hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7f8727e_1
    - zlib 1.2.12 h7f8727e_2
  run:
    - idna >=2.0
    - libgcc-ng >=11.2.0
    - multidict >=4.0
    - python >=3.9,<3.10.0a0
test:
  commands:
    - py.test tests
  requires:
    - pytest
  source_files:
    - tests
about:
  dev_url: https://github.com/aio-libs/yarl
  doc_source_url: https://github.com/aio-libs/yarl/tree/master/docs
  doc_url: https://yarl.readthedocs.io
  home: https://github.com/aio-libs/yarl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  license_url: https://www.apache.org/licenses/LICENSE-2.0
  summary: Yet another URL library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: c60569c7-01eb-463b-8109-427e9dc6e6fb
  recipe-maintainers:
    - sodre
  remote_url: git@github.com:AnacondaRecipes/yarl-feedstock.git
  sha: 35baf2babb402501ade289fb0d803db981f5c0e3
